version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://root:password@mongodb:27017/labtest2?authSource=admin
      - JWT_SECRET=secret
    volumes:
      - './backend:/usr/src/app'
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        MODE: development
    ports:
      - "3000:3000"
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
    mongodb_data:
